### PR TITLE
Better Why.

### PR DESCRIPTION
**Pull request by elishasmil3**
image
image
image

### CODE REVIEW

**Comment by lancepioch** [comment]
Can you make that section a solid color: rgb(14, 165, 233)

and also update the link colors to be better visible

**Comment by elishasmil3** [comment]
image
image

what do you say about a dark color?

**Comment by notAreYouScared** [comment]
I'm honestly not a fan of how the icons look...

**Comment by elishasmil3** [comment]
@notAreYouScared 
https://www.figma.com/proto/1qLINvtaYYryHfSKqNXwcm/Pelican?node-id=1-2&t=ZcVv1FVSbUADiOxX-0&scaling=min-zoom&page-id=0%3A1
eT5qCgADK4FEzRSZiEiTM10fRf7tyQ1wz0JYUFGR

something like this?

**Comment by notAreYouScared** [comment]
Please use the tabler icons are already have...

**Comment by elishasmil3** [comment]
coolm, i'll update with it

**Comment by elishasmil3** [comment]
Info02

What do you say?

**Comment by elishasmil3** [comment]
Group 1 (1)
What do you say?

**Comment by elishasmil3** [comment]
ik, the icons and content ain't aligned properly inside the container.
I'll fix it up once I get to code.

**Comment by notAreYouScared** [comment]
Any update on this?

**Comment by elishasmil3** [comment]
I can edit the code, if you would confirm the design..

**Pull request closed without merging**
